
#
# RPC login details
#
host=127.0.0.1
port=8337

rpcuser=bit04101132.2
rpcpass=x


#
# mining details
#

threads=1

# periodic rate for requesting new work, if solution not found
scantime=60


#
# misc.
#

# not really used right now
logdir=/tmp/pyminer

# set to 1, to enable hashmeter output
hashmeter=1


